#!/usr/bin/env bash
# =============================================================================
# FleetBits — LXC Setup Script
# =============================================================================
# This script runs INSIDE the Debian 12 LXC container.
# It is called automatically by scripts/proxmox/ct/fleetbits.sh.
# You can also run it manually for re-installation:
#
#   FLEET_DOMAIN=fleet.yourdomain.com bash fleetbits-install.sh
#
# What this script does:
#   1. Installs Docker CE + Docker Compose v2
#   2. Clones FleetBits-platform from GitHub
#   3. Generates all secrets (passwords, JWT keys, etc.)
#   4. Writes secrets.env and docker-compose.override.behind-proxy.yml
#   5. Starts the Docker Compose stack
#   6. Creates the initial admin user in the Fleet API
#   7. Prints credentials and access URLs
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GRN='\033[0;32m'; YLW='\033[1;33m'; CYN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYN}[INFO]${NC}  $*"; }
success() { echo -e "${GRN}[OK]${NC}    $*"; }
warn()    { echo -e "${YLW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# FLEET_DOMAIN must be set by the calling script (ct/fleetbits.sh) or explicitly:
#   FLEET_DOMAIN=fleet.yourdomain.com bash fleetbits-install.sh
[[ -n "${FLEET_DOMAIN:-}" ]] || { echo "[ERROR] FLEET_DOMAIN is not set. Run via ct/fleetbits.sh." >&2; exit 1; }
FLEET_DOMAIN="${FLEET_DOMAIN}"
INSTALL_DIR="/opt/fleetbits"
PLATFORM_REPO="https://github.com/NaejEL/FleetBits-platform.git"
COMPOSE_DIR="${INSTALL_DIR}/FleetBits-platform/docker"

# ── System packages ────────────────────────────────────────────────────────────
info "Installing system dependencies..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
    ca-certificates curl gnupg git openssl jq pwgen iproute2 \
    python3 python3-pip

# ── Docker CE ──────────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
    info "Installing Docker CE..."
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/debian $(. /etc/os-release && echo "${VERSION_CODENAME}") stable" \
        > /etc/apt/sources.list.d/docker.list

    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
    systemctl enable --now docker
    success "Docker CE installed."
else
    success "Docker already installed: $(docker --version)"
fi

# ── Clone platform repo ────────────────────────────────────────────────────────
info "Cloning FleetBits-platform..."
mkdir -p "${INSTALL_DIR}"
if [ -d "${INSTALL_DIR}/FleetBits-platform" ]; then
    warn "Repository already exists, pulling latest..."
    git -C "${INSTALL_DIR}/FleetBits-platform" pull --ff-only
else
    git clone "${PLATFORM_REPO}" "${INSTALL_DIR}/FleetBits-platform"
fi
success "Repository ready at ${INSTALL_DIR}/FleetBits-platform"

# ── Generate secrets ───────────────────────────────────────────────────────────
info "Generating secrets..."

gen_password() { openssl rand -base64 24 | tr -d '=+/'; }
gen_hex()      { openssl rand -hex 32; }
gen_jwt()      { openssl rand -base64 64 | tr -d '\n='; }

POSTGRES_PASSWORD=$(gen_password)
FLEET_DB_PASSWORD=$(gen_password)
SEMAPHORE_DB_PASSWORD=$(gen_password)
GRAFANA_ADMIN_PASSWORD=$(gen_password)
SEMAPHORE_API_KEY=$(gen_hex)
FLEET_JWT_SECRET=$(gen_jwt)
OPERATOR_PASSWORD=$(gen_password)

# Write secrets.env (readable only by root)
cat > "${COMPOSE_DIR}/../secrets.env" <<EOF
# ============================================================
# FleetBits Platform — Production secrets
# Generated by fleetbits-install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT — this file contains plaintext secrets
# ============================================================

FLEET_DOMAIN=${FLEET_DOMAIN}

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
FLEET_DB_PASSWORD=${FLEET_DB_PASSWORD}
SEMAPHORE_DB_PASSWORD=${SEMAPHORE_DB_PASSWORD}

GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

SEMAPHORE_API_KEY=${SEMAPHORE_API_KEY}

FLEET_JWT_SECRET=${FLEET_JWT_SECRET}

FLEET_API_INTERNAL_URL=http://fleet-api:8000
GRAFANA_INTERNAL_URL=http://grafana:3000

APTLY_GPG_KEY_ID=

FLEET_ENV=production

OPERATOR_USERNAME=admin
OPERATOR_PASSWORD=${OPERATOR_PASSWORD}
EOF
chmod 600 "${COMPOSE_DIR}/../secrets.env"
success "Secrets written to ${COMPOSE_DIR}/../secrets.env"

# ── GPG key for Aptly signing ──────────────────────────────────────────────────
info "Generating GPG key for Aptly package signing..."
if ! gpg --list-keys "fleet@${FLEET_DOMAIN}" &>/dev/null; then
    gpg --batch --gen-key <<GPGEOF
%no-protection
Key-Type: RSA
Key-Length: 4096
Subkey-Type: RSA
Subkey-Length: 4096
Name-Real: FleetBits Apt
Name-Email: fleet@${FLEET_DOMAIN}
Expire-Date: 0
%commit
GPGEOF
    success "GPG key generated."
fi

GPG_KEY_ID=$(gpg --list-keys --with-colons "fleet@${FLEET_DOMAIN}" 2>/dev/null \
    | grep "^pub" | cut -d: -f5 | tail -c 9)

if [ -n "${GPG_KEY_ID}" ]; then
    # Update secrets.env with the key ID
    sed -i "s/^APTLY_GPG_KEY_ID=$/APTLY_GPG_KEY_ID=${GPG_KEY_ID}/" \
        "${COMPOSE_DIR}/../secrets.env"

    # Export public key for apt clients — place in the aptly public dir later
    mkdir -p "${COMPOSE_DIR}/aptly/public"
    gpg --export --armor "fleet@${FLEET_DOMAIN}" \
        > "${COMPOSE_DIR}/aptly/public/fleetbits.asc"
    success "GPG key ID: ${GPG_KEY_ID} — public key exported to aptly/public/fleetbits.asc"
else
    warn "Could not determine GPG key ID — Aptly repos will use unsigned packages."
fi

# ── Write behind-proxy Compose override ───────────────────────────────────────
info "Configuring for behind-proxy (HTTP-only Caddy) deployment..."
ln -sf \
    "${COMPOSE_DIR}/docker-compose.override.behind-proxy.yml" \
    "${COMPOSE_DIR}/docker-compose.override.yml"
success "docker-compose.override.yml → behind-proxy override"

# ── Pull images & start the stack ─────────────────────────────────────────────
info "Pulling Docker images..."
cd "${COMPOSE_DIR}"
docker compose --env-file ../secrets.env pull --quiet

info "Starting FleetBits stack..."
docker compose --env-file ../secrets.env up -d

success "Stack started. Waiting for fleet-api to be ready..."
API_READY=false
for i in $(seq 1 90); do
    if curl -sf http://localhost:8000/healthz &>/dev/null; then
        API_READY=true
        success "Fleet API is healthy."
        break
    fi
    [ "${i}" -lt 90 ] || warn "Fleet API not ready after 180s — check: docker logs fleet-api"
    sleep 2
done

# ── Verify bootstrap admin login ───────────────────────────────────────────────
# The API seeds OPERATOR_USERNAME/OPERATOR_PASSWORD on first boot when users
# table is empty. Verify credentials instead of calling deprecated /auth/setup.
if [ "${API_READY}" = "true" ]; then
    info "Verifying bootstrap admin login in Fleet API..."
    if curl -sf -X POST http://localhost:8000/api/v1/auth/login \
        -H 'Content-Type: application/json' \
        -d "{\"username\":\"admin\",\"password\":\"${OPERATOR_PASSWORD}\"}" \
        &>/dev/null; then
        success "Bootstrap admin credentials verified."
    else
        warn "Could not verify admin login automatically (existing DB/user may have different password)."
    fi
else
    warn "Skipping admin login verification because Fleet API is not ready yet."
fi

# ── Create a systemd service for auto-start ────────────────────────────────────
info "Creating fleetbits.service for auto-start..."
cat > /etc/systemd/system/fleetbits.service <<EOF
[Unit]
Description=FleetBits Platform (Docker Compose)
Requires=docker.service
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${COMPOSE_DIR}
ExecStart=docker compose --env-file ../secrets.env up -d
ExecStop=docker compose --env-file ../secrets.env down
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable fleetbits.service
success "fleetbits.service enabled — stack will auto-start on boot."

# ── Auto-login root on tty1 (Proxmox console) ─────────────────────────────────
info "Configuring auto-login root on tty1..."
mkdir -p /etc/systemd/system/getty@tty1.service.d
cat > /etc/systemd/system/getty@tty1.service.d/autologin.conf <<'EOF'
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin root --noclear %I $TERM
EOF
systemctl daemon-reload
success "Auto-login configured — Proxmox console will log in as root automatically."

# ── Set root password (shown in install summary for SSH access if needed) ────────
ROOT_PASSWORD=$(gen_password)
echo "root:${ROOT_PASSWORD}" | chpasswd
success "Root password set."

# ── Install update script ──────────────────────────────────────────────────────
cp "${INSTALL_DIR}/FleetBits-platform/scripts/update.sh" /usr/local/bin/fleetbits-update
chmod +x /usr/local/bin/fleetbits-update
success "Update script installed at /usr/local/bin/fleetbits-update"

# ── Print credentials ──────────────────────────────────────────────────────────
CT_IP=$(hostname -I | awk '{print $1}')

echo ""
echo -e "${GRN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GRN}║              FleetBits Installation Complete                 ║${NC}"
echo -e "${GRN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Container IP:     ${CT_IP}"
echo -e "  Install dir:      ${INSTALL_DIR}"
echo -e "  Secrets file:     ${INSTALL_DIR}/secrets.env"
echo ""
echo -e "  ${YLW}Fleet UI credentials:${NC}"
echo -e "    URL:         https://${FLEET_DOMAIN}"
echo -e "    Username:    admin"
echo -e "    Password:    ${OPERATOR_PASSWORD}"
echo ""
echo -e "  ${YLW}Grafana credentials:${NC}"
echo -e "    URL:         https://grafana.${FLEET_DOMAIN}"
echo -e "    Username:    admin"
echo -e "    Password:    ${GRAFANA_ADMIN_PASSWORD}"
echo ""
echo -e "  ${YLW}Semaphore credentials:${NC}"
echo -e "    URL:         https://semaphore.${FLEET_DOMAIN}"
echo -e "    Username:    admin"
echo -e "    Password:    ${GRAFANA_ADMIN_PASSWORD}  (same as Grafana admin)"
echo ""
echo -e "  ${YLW}Aptly repo (public key for apt clients):${NC}"
echo -e "    https://repo.${FLEET_DOMAIN}/fleetbits.asc"
echo ""
echo -e "  ${YLW}Reverse proxy (Nginx Proxy Manager):${NC}"
echo -e "    Add these proxy hosts in NPM pointing to CT IP: ${CT_IP}"
echo -e "    ${FLEET_DOMAIN}             → http://${CT_IP}:80"
echo -e "    grafana.${FLEET_DOMAIN}     → http://${CT_IP}:80"
echo -e "    api.${FLEET_DOMAIN}         → http://${CT_IP}:80"
echo -e "    repo.${FLEET_DOMAIN}        → http://${CT_IP}:80"
echo -e "    headscale.${FLEET_DOMAIN}   → http://${CT_IP}:80"
echo -e "    semaphore.${FLEET_DOMAIN}   → http://${CT_IP}:80"
echo -e "    metrics.${FLEET_DOMAIN}     → http://${CT_IP}:80"
echo -e "    logs.${FLEET_DOMAIN}        → http://${CT_IP}:80"
echo -e "    Enable \"Websockets Support\" for grafana and semaphore hosts."
echo ""
echo -e "  ${YLW}To update FleetBits in the future:${NC}"
echo -e "    fleetbits-update"
echo ""

# Save credentials to a file for reference
cat > "${INSTALL_DIR}/credentials.txt" <<EOF
# FleetBits Platform — Credentials
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# KEEP THIS FILE SECURE

Fleet UI
  URL:      https://${FLEET_DOMAIN}
  Username: admin
  Password: ${OPERATOR_PASSWORD}

Grafana
  URL:      https://grafana.${FLEET_DOMAIN}
  Username: admin
  Password: ${GRAFANA_ADMIN_PASSWORD}

Semaphore
  URL:      https://semaphore.${FLEET_DOMAIN}
  Username: admin
  Password: ${GRAFANA_ADMIN_PASSWORD}

Root (SSH / console fallback)
  Username: root
  Password: ${ROOT_PASSWORD}

PostgreSQL
  postgres password: ${POSTGRES_PASSWORD}
  fleet db password: ${FLEET_DB_PASSWORD}

Aptly GPG Key ID: ${GPG_KEY_ID:-"(not generated)"}
EOF
chmod 600 "${INSTALL_DIR}/credentials.txt"
success "Credentials saved to ${INSTALL_DIR}/credentials.txt"

# ── Optional: enroll VPS as a fleet device (self-monitoring) ──────────────────
echo ""
read -rp "$(echo -e "${YLW}[?]${NC}   Enroll this VPS as a fleet device for self-monitoring? [y/N]: ")" ENROLL_VPS
if [[ "${ENROLL_VPS,,}" == "y" ]]; then
    info "Re-checking Fleet API readiness before enrollment..."
    if ! curl -sf http://localhost:8000/healthz &>/dev/null; then
        warn "Fleet API still not reachable. Skipping enrollment for now."
        warn "Retry later with: bash ${INSTALL_DIR}/FleetBits-platform/scripts/enroll-vps.sh --api-url http://localhost:8000 --secrets ${INSTALL_DIR}/FleetBits-platform/secrets.env"
        exit 0
    fi

    info "Cloning FleetBits-agent (required to build the vps-device container)..."
    if [ -d "${INSTALL_DIR}/FleetBits-agent" ]; then
        git -C "${INSTALL_DIR}/FleetBits-agent" pull --ff-only
    else
        git clone https://github.com/NaejEL/FleetBits-agent.git "${INSTALL_DIR}/FleetBits-agent"
    fi
    success "FleetBits-agent cloned."

    info "Running VPS enrollment script..."
    bash "${INSTALL_DIR}/FleetBits-platform/scripts/enroll-vps.sh" \
        --api-url http://localhost:8000 \
        --secrets "${INSTALL_DIR}/FleetBits-platform/secrets.env"

    info "Starting vps-device container..."
    cd "${COMPOSE_DIR}"
    docker compose --profile agent --env-file ../secrets.env up -d --build vps-device
    success "vps-device started — VPS is now a managed fleet device."

    # Patch fleetbits.service so vps-device also starts on every reboot
    sed -i \
        's|ExecStart=docker compose --env-file ../secrets.env up -d$|ExecStart=docker compose --profile agent --env-file ../secrets.env up -d|' \
        /etc/systemd/system/fleetbits.service
    sed -i \
        's|ExecStop=docker compose --env-file ../secrets.env down$|ExecStop=docker compose --profile agent --env-file ../secrets.env down|' \
        /etc/systemd/system/fleetbits.service
    systemctl daemon-reload
    success "fleetbits.service updated — vps-device will auto-start on reboot."
else
    info "Skipped. To enable VPS self-monitoring later, run:"
    echo "  bash ${INSTALL_DIR}/FleetBits-platform/scripts/enroll-vps.sh"
fi
