#!/usr/bin/env bash
# ============================================================
# FleetBits — Local Dev Setup (Linux / macOS)
#
# Usage:
#   ./dev-setup.sh            # first run
#   ./dev-setup.sh --force    # overwrite existing secrets
#   ./dev-setup.sh --no-build # write config files only, skip compose up
#
# Requires: bash ≥4, docker (with compose plugin), openssl
# ============================================================

set -euo pipefail

# ── Flags ─────────────────────────────────────────────────────────────────────

FORCE=0
NO_BUILD=0

for arg in "$@"; do
    case "$arg" in
        --force)    FORCE=1 ;;
        --no-build) NO_BUILD=1 ;;
        *)
            echo "Unknown argument: $arg"
            echo "Usage: $0 [--force] [--no-build]"
            exit 1
            ;;
    esac
done

# ── Colour helpers ────────────────────────────────────────────────────────────

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
WHITE='\033[1;37m'
RESET='\033[0m'

step()  { echo -e "\n${CYAN}==> $*${RESET}"; }
ok()    { echo -e "    ${GREEN}✓ $*${RESET}"; }
warn()  { echo -e "    ${YELLOW}~ $* (already exists — use --force to overwrite)${RESET}"; }
err()   { echo -e "${RED}ERROR: $*${RESET}" >&2; exit 1; }

# ── Helpers ───────────────────────────────────────────────────────────────────

rand_base64() { openssl rand -base64 "$1"; }   # $1 = byte count
rand_hex()    { openssl rand -hex   "$1"; }    # $1 = byte count

# Read a KEY=VALUE from an existing env file; returns empty string if not found.
read_env() {
    local file="$1" key="$2"
    grep -m1 "^${key}=" "$file" 2>/dev/null | cut -d'=' -f2- || true
}

# ── Locate repos ──────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"   # FleetBits-platform/
DOCKER_DIR="$REPO_ROOT/docker"
API_REPO="$(dirname "$REPO_ROOT")/FleetBits-api"
UI_REPO="$(dirname "$REPO_ROOT")/FleetBits-ui"
SECRETS_ENV="$REPO_ROOT/secrets.env"
OVERRIDE="$DOCKER_DIR/docker-compose.override.yml"

echo ""
echo -e "${WHITE}FleetBits — Local Dev Setup${RESET}"
echo "Platform root : $REPO_ROOT"
echo "Docker dir    : $DOCKER_DIR"
echo "API repo      : $API_REPO"

# ── Prerequisites ─────────────────────────────────────────────────────────────

step "Checking prerequisites"

command -v openssl &>/dev/null || err "openssl not found. Install it and retry."
ok "openssl found"

if ! docker info &>/dev/null; then
    err "Docker is not running or not installed."
fi
ok "Docker is running"

[[ -d "$DOCKER_DIR" ]] || err "docker/ directory not found at $DOCKER_DIR"
ok "docker/ directory found"

API_AVAILABLE=0
if [[ -d "$API_REPO" ]]; then
    ok "FleetBits-api repo found"
    API_AVAILABLE=1
else
    echo -e "    ${YELLOW}WARNING: FleetBits-api repo not found at $API_REPO${RESET}"
    echo    "             The fleet-api container will NOT be built from source."
    echo    "             Clone it as a sibling to FleetBits-platform and re-run."
fi

UI_AVAILABLE=0
if [[ -d "$UI_REPO" ]]; then
    ok "FleetBits-ui repo found"
    UI_AVAILABLE=1
else
    echo -e "    ${YELLOW}WARNING: FleetBits-ui repo not found at $UI_REPO${RESET}"
fi

# ── Generate secrets ──────────────────────────────────────────────────────────

step "Generating secrets"

POSTGRES_PASSWORD=$(rand_base64 18)
FLEET_DB_PASSWORD=$(rand_base64 18)
SEMAPHORE_DB_PASSWORD=$(rand_base64 18)
GRAFANA_ADMIN_PASSWORD=$(rand_base64 18)
SEMAPHORE_API_KEY=$(rand_hex 32)
FLEET_JWT_SECRET=$(rand_base64 48)
OPERATOR_PASSWORD=$(rand_base64 16)

ok "Secrets generated"

# ── Write secrets.env ─────────────────────────────────────────────────────────

step "Writing secrets.env"

if [[ -f "$SECRETS_ENV" && "$FORCE" -eq 0 ]]; then
    warn "secrets.env"
    # Preserve existing values for downstream .env files
    existing_jwt=$(read_env "$SECRETS_ENV" FLEET_JWT_SECRET)
    existing_key=$(read_env "$SECRETS_ENV" SEMAPHORE_API_KEY)
    existing_db=$(read_env  "$SECRETS_ENV" FLEET_DB_PASSWORD)
    existing_pw=$(read_env  "$SECRETS_ENV" OPERATOR_PASSWORD)
    [[ -n "$existing_jwt" ]] && FLEET_JWT_SECRET="$existing_jwt"
    [[ -n "$existing_key" ]] && SEMAPHORE_API_KEY="$existing_key"
    [[ -n "$existing_db"  ]] && FLEET_DB_PASSWORD="$existing_db"
    [[ -n "$existing_pw"  ]] && OPERATOR_PASSWORD="$existing_pw"
else
    cat > "$SECRETS_ENV" <<EOF
# ============================================================
# FleetBits Platform — LOCAL DEV secrets
# Generated by dev-setup.sh — DO NOT COMMIT
# ============================================================

FLEET_DOMAIN=localhost

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
FLEET_DB_PASSWORD=${FLEET_DB_PASSWORD}
SEMAPHORE_DB_PASSWORD=${SEMAPHORE_DB_PASSWORD}

GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

SEMAPHORE_API_KEY=${SEMAPHORE_API_KEY}

FLEET_JWT_SECRET=${FLEET_JWT_SECRET}

FLEET_API_INTERNAL_URL=http://fleet-api:8000
GRAFANA_INTERNAL_URL=http://grafana:3000

APTLY_GPG_KEY_ID=

FLEET_ENV=development

# Operator login for Fleet UI (written to FleetBits-api/.env by this script)
OPERATOR_USERNAME=admin
OPERATOR_PASSWORD=${OPERATOR_PASSWORD}
EOF
    ok "secrets.env written  (operator login: admin / ${OPERATOR_PASSWORD})"
fi

# ── Write docker-compose.override.yml ─────────────────────────────────────────

step "Writing docker/docker-compose.override.yml"

if [[ -f "$OVERRIDE" && "$FORCE" -eq 0 ]]; then
    warn "docker-compose.override.yml"
else
    {
        cat <<'HEADER'
# docker-compose.override.yml — LOCAL DEV
# Generated by dev-setup.sh — DO NOT COMMIT

services:
  caddy:
    # Use the dev Caddyfile (plain HTTP, no TLS).
    # ./caddy/ is already mounted to /etc/caddy/ by the base compose.
    command: caddy run --config /etc/caddy/Caddyfile.dev --adapter caddyfile
    environment:
      FLEET_DOMAIN: "localhost"

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_ROOT_URL: "http://localhost:3000"
      GF_SERVER_SERVE_FROM_SUB_PATH: "false"

  loki:
    ports:
      - "3100:3100"

  alertmanager:
    ports:
      - "9093:9093"

  semaphore:
    ports:
      - "3001:3000"

  postgresql:
    ports:
      - "5432:5432"
HEADER

        if [[ "$API_AVAILABLE" -eq 1 ]]; then
            cat <<'API'

  fleet-api:
    build:
      context: ../../FleetBits-api
      dockerfile: Dockerfile
    image: fleetbits-api:dev
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://fleet:${FLEET_DB_PASSWORD}@postgresql:5432/fleet"
      FLEET_ENV: "development"
      FLEET_API_URL: "http://localhost:8000"
      OPERATOR_USERNAME: "${OPERATOR_USERNAME}"
      OPERATOR_PASSWORD: "${OPERATOR_PASSWORD}"
API
        fi

        if [[ "$UI_AVAILABLE" -eq 1 ]]; then
            cat <<'UI'

  fleet-ui:
    build:
      context: ../../FleetBits-ui
      dockerfile: Dockerfile
    image: fleetbits-ui:dev
    ports:
      - "5000:5000"
    environment:
      FLEET_API_URL: "http://fleet-api:8000"
      GRAFANA_URL: "http://grafana:3000"
      SEMAPHORE_URL: "http://localhost:3001"
      FLEET_ENV: "development"
      SECRET_KEY: "${FLEET_JWT_SECRET}"
UI
        fi
    } > "$OVERRIDE"
    ok "docker-compose.override.yml written"
fi

# ── Write FleetBits-api/.env ──────────────────────────────────────────────────

if [[ "$API_AVAILABLE" -eq 1 ]]; then
    step "Writing FleetBits-api/.env"
    API_ENV="$API_REPO/.env"
    if [[ -f "$API_ENV" && "$FORCE" -eq 0 ]]; then
        warn "FleetBits-api/.env"
    else
        cat > "$API_ENV" <<EOF
# FleetBits API — local dev
# Generated by dev-setup.sh — DO NOT COMMIT

DATABASE_URL=postgresql+asyncpg://fleet:${FLEET_DB_PASSWORD}@localhost:5432/fleet

SEMAPHORE_URL=http://localhost:3001
SEMAPHORE_API_KEY=${SEMAPHORE_API_KEY}
SEMAPHORE_PROJECT_ID=1
SEMAPHORE_DEPLOY_TEMPLATE_ID=1
SEMAPHORE_ROLLBACK_TEMPLATE_ID=2
SEMAPHORE_RESTART_TEMPLATE_ID=3
SEMAPHORE_DIAGNOSTICS_TEMPLATE_ID=4
SEMAPHORE_LOGS_TEMPLATE_ID=5

FLEET_JWT_SECRET=${FLEET_JWT_SECRET}
FLEET_JWT_ALGORITHM=HS256
FLEET_JWT_EXPIRE_MINUTES=480

PROMETHEUS_URL=http://localhost:9090
LOKI_URL=http://localhost:3100
ALERTMANAGER_URL=http://localhost:9093

FLEET_ENV=development
FLEET_API_URL=http://localhost:8000

OPERATOR_USERNAME=admin
OPERATOR_PASSWORD=${OPERATOR_PASSWORD}
EOF
        ok "FleetBits-api/.env written"
    fi
fi

# ── Write FleetBits-ui/.env ───────────────────────────────────────────────────

if [[ "$UI_AVAILABLE" -eq 1 ]]; then
    step "Writing FleetBits-ui/.env"
    UI_ENV="$UI_REPO/.env"
    if [[ -f "$UI_ENV" && "$FORCE" -eq 0 ]]; then
        warn "FleetBits-ui/.env"
    else
        cat > "$UI_ENV" <<EOF
# FleetBits UI — local dev
# Generated by dev-setup.sh — DO NOT COMMIT

SECRET_KEY=${FLEET_JWT_SECRET}
FLEET_API_URL=http://localhost:8000
GRAFANA_URL=http://localhost:3000
SEMAPHORE_URL=http://localhost:3001
FLEET_DOMAIN=localhost
FLEET_ENV=development
EOF
        ok "FleetBits-ui/.env written"
    fi
fi

# ── docker compose up ─────────────────────────────────────────────────────────

if [[ "$NO_BUILD" -eq 1 ]]; then
    echo -e "\n${YELLOW}Skipping docker compose (--no-build passed).${RESET}"
else
    step "Starting stack  (docker compose up --build -d)"
    echo "    This may take a few minutes on first run while images are pulled/built."
    (cd "$DOCKER_DIR" && docker compose --env-file ../secrets.env up --build -d)
    ok "Stack is up"
fi

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo -e "${WHITE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${GREEN} FleetBits dev stack ready${RESET}"
echo -e "${WHITE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo "  Fleet UI        http://localhost        (login: admin / ${OPERATOR_PASSWORD})"
echo "  Fleet API docs  http://localhost:8000/docs"
echo "  Grafana         http://localhost:3000   (admin / ${GRAFANA_ADMIN_PASSWORD})"
echo "  Semaphore       http://localhost:3001"
echo "  Prometheus      http://localhost:9090"
echo ""
echo -e "${YELLOW}  Credentials are saved in secrets.env — keep it private.${RESET}"
echo ""
echo "  To stop:   cd docker && docker compose --env-file ../secrets.env down"
echo "  To reset:  ./dev-setup.sh --force"
echo ""
