#!/usr/bin/env bash
# =============================================================================
# generate-vault.sh — Bootstrap group_vars/all/vault.yml with random secrets
# =============================================================================
# Generates cryptographically random values for all auto-generatable vault keys
# and writes a cleartext vault.yml ready for ansible-vault encryption.
#
# Usage:
#   bash scripts/generate-vault.sh [--vault-dir PATH] [--encrypt]
#
# Options:
#   --vault-dir PATH   Path to the directory containing vault.yml.example
#                      Default: ansible/group_vars/all
#   --encrypt          Encrypt the output file with ansible-vault immediately
#                      (prompts for vault password)
#
# Requirements: openssl
# Optional:     ansible-vault (only needed with --encrypt)
#
# Keys requiring manual input after generation (left as CHANGE_ME):
#   vault_headscale_preauth_key       — run after headscale starts
#   vault_fleet_bootstrap_token_paris — run after fleet-api starts
#   vault_fleet_bootstrap_token_lyon  — run after fleet-api starts
#   vault_custom_soft_api_key         — site-specific external API key
#   vault_zone_controller_license     — vendor-provided licence string
#   vault_video_player_license_key    — vendor-provided licence string
# =============================================================================

set -euo pipefail

# ── Colour helpers ─────────────────────────────────────────────────────────────
CYN='\033[0;36m'; GRN='\033[0;32m'; YLW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()    { echo -e "${CYN}[INFO]${NC}  $*"; }
success() { echo -e "${GRN}[OK]${NC}    $*"; }
warn()    { echo -e "${YLW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Defaults ───────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VAULT_DIR="${SCRIPT_DIR}/../ansible/group_vars/all"
ENCRYPT=false

# ── Argument parsing ───────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --vault-dir) VAULT_DIR="$2"; shift 2 ;;
        --encrypt)   ENCRYPT=true; shift ;;
        *) error "Unknown argument: $1. Usage: $0 [--vault-dir PATH] [--encrypt]" ;;
    esac
done

VAULT_EXAMPLE="${VAULT_DIR}/vault.yml.example"
VAULT_OUT="${VAULT_DIR}/vault.yml"

[ -f "${VAULT_EXAMPLE}" ] || error "vault.yml.example not found at: ${VAULT_EXAMPLE}"
command -v openssl &>/dev/null || error "openssl is required but not installed."
if "${ENCRYPT}"; then
    command -v ansible-vault &>/dev/null || error "ansible-vault is required for --encrypt but not found."
fi

# ── Helper: generate a random password ────────────────────────────────────────
# openssl rand -base64 N | tr removes padding characters that cause shell quoting issues
randpass() {
    local bytes="${1:-32}"
    openssl rand -base64 "${bytes}" | tr -d '=+/' | head -c "${bytes}"
}

# ── Guard against overwriting ─────────────────────────────────────────────────
if [[ -f "${VAULT_OUT}" ]]; then
    warn "vault.yml already exists at: ${VAULT_OUT}"
    read -rp "Overwrite? [y/N]: " confirm
    [[ "${confirm}" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }
fi

echo ""
echo -e "${CYN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${CYN}║        FleetBits — Generate Vault Secrets        ║${NC}"
echo -e "${CYN}╚══════════════════════════════════════════════════╝${NC}"
echo ""

# ── Generate values ────────────────────────────────────────────────────────────
info "Generating random secrets..."

VAULT_APTLY_GPG_KEY_PASSPHRASE="$(randpass 32)"
VAULT_POSTGRES_PASSWORD="$(randpass 32)"
VAULT_FLEET_DB_PASSWORD="$(randpass 32)"
VAULT_SEMAPHORE_DB_PASSWORD="$(randpass 32)"
VAULT_GRAFANA_ADMIN_PASSWORD="$(randpass 24)"
# Semaphore API key: 32-char alphanumeric (its UI accepts any string; matches its own format)
VAULT_SEMAPHORE_API_KEY="$(openssl rand -hex 16)"
VAULT_MQTT_BROKER_PASSWORD="$(randpass 32)"

success "7 random secrets generated."

# ── Write vault.yml ────────────────────────────────────────────────────────────
info "Writing ${VAULT_OUT}..."

cat > "${VAULT_OUT}" <<EOF
---
# group_vars/all/vault.yml
# Generated by generate-vault.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Keys marked CHANGE_ME require manual input — see comments.
# Encrypt this file before committing: ansible-vault encrypt group_vars/all/vault.yml

# ── aptly GPG signing key ──────────────────────────────────────────────────
vault_aptly_gpg_key_passphrase: "${VAULT_APTLY_GPG_KEY_PASSPHRASE}"

# ── PostgreSQL ─────────────────────────────────────────────────────────────
vault_postgres_password:     "${VAULT_POSTGRES_PASSWORD}"
vault_fleet_db_password:     "${VAULT_FLEET_DB_PASSWORD}"
vault_semaphore_db_password: "${VAULT_SEMAPHORE_DB_PASSWORD}"

# ── Grafana ────────────────────────────────────────────────────────────────
vault_grafana_admin_password: "${VAULT_GRAFANA_ADMIN_PASSWORD}"

# ── Semaphore ──────────────────────────────────────────────────────────────
vault_semaphore_api_key: "${VAULT_SEMAPHORE_API_KEY}"

# ── Headscale enrollment ───────────────────────────────────────────────────
# Generate after headscale is running:
#   docker compose -f docker/docker-compose.yml exec headscale \
#     headscale preauthkeys create --user fleet --reusable=true --expiration 24h
vault_headscale_preauth_key: "CHANGE_ME"

# ── Fleet API bootstrap tokens ─────────────────────────────────────────────
# Generate after fleet-api is running:
#   bash scripts/enroll-vps.sh  (issues operator JWT automatically)
# Or:
#   curl -s -X POST http://localhost:8000/api/v1/auth/login \
#     -H 'Content-Type: application/json' \
#     -d '{"username":"...","password":"..."}' | jq -r '.access_token'
vault_fleet_bootstrap_token_paris: "CHANGE_ME"
vault_fleet_bootstrap_token_lyon:  "CHANGE_ME"

# ── Application software secrets (site-specific — fill in as needed) ───────
vault_custom_soft_api_key:     "CHANGE_ME"
vault_zone_controller_license: "CHANGE_ME"
vault_mqtt_broker_password:    "${VAULT_MQTT_BROKER_PASSWORD}"
vault_video_player_license_key: "CHANGE_ME"
EOF

success "vault.yml written."

# ── Print summary ──────────────────────────────────────────────────────────────
echo ""
echo "  Generated automatically (7 keys):"
echo "    vault_aptly_gpg_key_passphrase"
echo "    vault_postgres_password"
echo "    vault_fleet_db_password"
echo "    vault_semaphore_db_password"
echo "    vault_grafana_admin_password"
echo "    vault_semaphore_api_key"
echo "    vault_mqtt_broker_password"
echo ""
echo "  Requires manual input (6 keys — search for CHANGE_ME in vault.yml):"
echo "    vault_headscale_preauth_key       — after headscale is running"
echo "    vault_fleet_bootstrap_token_paris — after fleet-api is running"
echo "    vault_fleet_bootstrap_token_lyon  — after fleet-api is running"
echo "    vault_custom_soft_api_key         — site-specific external API key"
echo "    vault_zone_controller_license     — vendor-provided licence"
echo "    vault_video_player_license_key    — vendor-provided licence"
echo ""

# ── Encrypt ────────────────────────────────────────────────────────────────────
if "${ENCRYPT}"; then
    info "Encrypting vault.yml with ansible-vault..."
    ansible-vault encrypt "${VAULT_OUT}"
    success "vault.yml encrypted in-place."
else
    warn "vault.yml is UNENCRYPTED. Encrypt it before committing:"
    echo "    ansible-vault encrypt ${VAULT_OUT}"
fi

echo ""
echo -e "${GRN}Done!${NC}"
